import * as React from 'react';
import { JSX } from 'react/jsx-runtime';
const SvgAppsOutline = (
  props: JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>
) => (
  <svg
    xmlns='http://www.w3.org/2000/svg'
    className='apps-outline_svg__ionicon'
    viewBox='0 0 512 512'
    width='1em'
    height='1em'
    {...props}
  >
    <rect
      width={80}
      height={80}
      x={64}
      y={64}
      fill='none'
      stroke='currentColor'
      strokeMiterlimit={10}
      strokeWidth={32}
      rx={40}
      ry={40}
    />
    <rect
      width={80}
      height={80}
      x={216}
      y={64}
      fill='none'
      stroke='currentColor'
      strokeMiterlimit={10}
      strokeWidth={32}
      rx={40}
      ry={40}
    />
    <rect
      width={80}
      height={80}
      x={368}
      y={64}
      fill='none'
      stroke='currentColor'
      strokeMiterlimit={10}
      strokeWidth={32}
      rx={40}
      ry={40}
    />
    <rect
      width={80}
      height={80}
      x={64}
      y={216}
      fill='none'
      stroke='currentColor'
      strokeMiterlimit={10}
      strokeWidth={32}
      rx={40}
      ry={40}
    />
    <rect
      width={80}
      height={80}
      x={216}
      y={216}
      fill='none'
      stroke='currentColor'
      strokeMiterlimit={10}
      strokeWidth={32}
      rx={40}
      ry={40}
    />
    <rect
      width={80}
      height={80}
      x={368}
      y={216}
      fill='none'
      stroke='currentColor'
      strokeMiterlimit={10}
      strokeWidth={32}
      rx={40}
      ry={40}
    />
    <rect
      width={80}
      height={80}
      x={64}
      y={368}
      fill='none'
      stroke='currentColor'
      strokeMiterlimit={10}
      strokeWidth={32}
      rx={40}
      ry={40}
    />
    <rect
      width={80}
      height={80}
      x={216}
      y={368}
      fill='none'
      stroke='currentColor'
      strokeMiterlimit={10}
      strokeWidth={32}
      rx={40}
      ry={40}
    />
    <rect
      width={80}
      height={80}
      x={368}
      y={368}
      fill='none'
      stroke='currentColor'
      strokeMiterlimit={10}
      strokeWidth={32}
      rx={40}
      ry={40}
    />
  </svg>
);
export default SvgAppsOutline;
